### ISSUE TITLE
Neagtive y axis not possible

### ISSUE THREAD

**Issue by robhankin** [haroutboujakjian/Vuesalize#7]
I have tried y-min and y-max but nothing allows the y axis to show a negative scale even though negative data plots successfully. Thanks

**Comment by haroutboujakjian** [comment]
@robhankin sorry to hear that's not working. Is there a specific chart where the y-axis isn't showing?

**Comment by robhankin** [comment]
Hey @haroutboujakjian it is the AreaChart. Apologies, I haven't tried the others. Great job by the way.

**Comment by haroutboujakjian** [comment]
@robhankin Yeah it looks like this is broken. I should be able to get a fix out by tomorrow or the next day!

**Comment by robhankin** [comment]
That's amazing. Thank you

**Comment by haroutboujakjian** [comment]
Hey @robhankin, I just added the `y-min` and `y-max` props to the area chart. You should be able to adjust the `y-min` value to have negative axis values now. Please test it out when you get a chance and let me know if it's working.

**Comment by haroutboujakjian** [comment]
@robhankin have you had an opportunity to test out the new release? If things are working, then let's close out this issue.
